import 'dart:math';

class UatDummyData {
  static final Random _random = Random();

  static final List<Map<String, dynamic>> _dummyPosts = [
    {
      'title': 'My Journey to Recovery: Celebrating Six Months Cancer-Free',
      'content': 'It’s been an incredible journey over the last six months. From the moment I was first diagnosed, everything felt overwhelming and uncertain. There were days when getting out of bed felt like a monumental task, and times when the treatment took everything out of me. The hospital visits blurred together into a seemingly endless routine of waiting rooms, IV drips, and sympathetic glances from nurses who had seen it all before. But with the unwavering support of my family, my incredible medical team, and the stories shared by this community, I found the strength to keep fighting. Today, I am officially six months in remission.\n\nI wanted to share this milestone to remind anyone else currently going through treatment that there is always hope. Keep pushing forward, take it one day at a time, and never underestimate the power of a positive mindset and a strong support system. When I first started chemotherapy, I lost my hair and my appetite, but I learned to find joy in small moments—like watching the sunrise or having a warm cup of tea. Connecting with others who understood exactly what I was feeling made all the difference in the world. \n\nRecovery isn\'t just a physical battle; it\'s a mental one too. Some days I still struggle with anxiety about the future, wondering if every ache or pain is a sign that the disease has returned. But I try to ground myself in the present. I\'ve started doing yoga, eating healthier, and taking long walks in nature. The crisp morning air feels like a privilege now, rather than just weather. Every day is a gift. If you are reading this and feeling scared, just know that you are stronger than you think. We are all in this together, and healing is not a linear process.',
      'tags': ['CancerFree', 'Remission', 'HealingJourney', 'Survivor', 'Milestone'],
    },
    {
      'title': 'Finding Peace After a Heart Attack: My New Normal',
      'content': 'Two years ago, my life changed forever when I suffered a major heart attack at the age of 45. I thought I was healthy, but stress and a poor diet caught up with me. The recovery process was the hardest thing I\'ve ever gone through, both physically and emotionally. The fear of another cardiac event hovered over me like a dark cloud for months, paralyzing me from doing even the simplest of tasks like lifting groceries or walking up a flight of stairs. \n\nToday, I walked my first 5K! It might not seem like a lot to some, but to me, it\'s a monumental achievement. Cardiac rehab taught me how to trust my body again, slowly reintroducing physical exertion in a safe, monitored environment. The nurses and therapists at the clinic were my guiding lights, reminding me that my heart was a muscle that needed to be trained, not hidden away in a box of bubble wrap. \n\nI’ve completely overhauled my diet, cutting out processed foods and focusing on heart-healthy meals rich in omega-3s, leafy greens, and whole grains. More importantly, I’ve learned to manage my stress. I meditate daily, I prioritize my sleep, and I no longer let work consume my life. The emails can wait until tomorrow. \n\nTo anyone out there recovering from a cardiac event: be patient with yourself. Healing takes time. Celebrate the small victories, whether it\'s walking to the end of the driveway, cooking a healthy meal, or simply having a good day where the fear doesn\'t consume you. You will find your new normal, and in many ways, it might be a healthier, more balanced normal than the one you left behind.',
      'tags': ['HeartHealth', 'CardiacRehab', 'HealthyLifestyle', 'Recovery', 'Milestone'],
    },
    {
      'title': 'Living with Chronic Pain: A Message of Solidarity',
      'content': 'For the past five years, I have lived with severe endometriosis. Chronic pain is invisible, and that makes it incredibly isolating. Many people don’t understand why I have to cancel plans at the last minute or why I look perfectly healthy but feel like my body is at war with itself. The sheer exhaustion of masking the pain just to get through a workday is something only fellow chronic pain sufferers can truly comprehend.\n\nI wanted to post today to say that if you are living with an invisible illness, I see you. Your pain is valid. It took me three years and four different doctors just to get a diagnosis. I was told repeatedly that my symptoms were normal, that I was just stressed, or that it was "all in my head." Advocating for yourself in the medical system is exhausting, but please don’t give up until you find a doctor who listens to you.\n\nI’ve found that joining support groups and connecting with others who share my condition has been an absolute lifesaver. We share tips on pain management—from heating pads to specific dietary changes—vent our frustrations, and celebrate the days when the pain is manageable. \n\nLiving with a chronic condition means grieving the healthy body you thought you were going to have. But it also means discovering a profound resilience within yourself. Be kind to your body; it is doing the best it can under incredibly difficult circumstances. You are not alone in this fight.',
      'tags': ['ChronicPain', 'Endometriosis', 'InvisibleIllness', 'HealingJourney'],
    },
    {
      'title': 'The Road to Mental Wellness: One Step at a Time',
      'content': 'Taking medication for my depression and anxiety was a decision that took me years to make. I let stigma and fear hold me back, convinced that I just needed to "try harder" or that I could exercise and meditate my way out of a chemical imbalance in my brain. I hit rock bottom last winter, unable to leave my apartment or answer messages from friends, and finally sought professional help.\n\nI’ve been on my treatment plan for eight months now, combined with weekly cognitive behavioral therapy sessions. The fog has finally started to lift. I can enjoy my hobbies again, and getting out of bed is no longer a daily battle of will. I actually look forward to my morning coffee, the sound of the birds, and the prospect of a new day—things that felt entirely meaningless just a year ago.\n\nI’m sharing this because I want to normalize seeking help for mental health. Taking medication for your brain is absolutely no different than taking insulin for diabetes or wearing glasses to correct your vision. The brain is an organ, and sometimes it needs medical intervention to function properly.\n\nIf you are struggling in silence, please reach out to someone. A therapist, a doctor, a trusted friend, or a hotline. Healing is not linear—I still have bad days, days where the old shadows try to creep back in—but the good days finally outnumber the bad ones, and I now have the tools to handle the bad ones when they arrive.',
      'tags': ['MentalHealth', 'DepressionRecovery', 'TherapyWorks', 'Recovery'],
    },
    {
      'title': 'Navigating Life with Type 1 Diabetes',
      'content': 'Managing Type 1 Diabetes is a full-time job that you never get a vacation from. Counting carbs, adjusting insulin, monitoring blood sugar—it’s exhausting. When I was diagnosed at 22, I felt like my life was over. I thought I would never be able to eat a piece of cake again, travel spontaneously, or engage in intense physical activities without fear of a dangerous hypoglycemic episode.\n\nBut ten years later, I can confidently say that I am thriving. Technology has been an absolute game changer. Getting a continuous glucose monitor (CGM) and a closed-loop insulin pump gave me back so much freedom. I no longer have to prick my fingers ten times a day, and the pump adjusts my basal rates automatically while I sleep, preventing those terrifying overnight lows.\n\nI’m currently training for a half marathon, something I never thought possible when I was first diagnosed. It requires meticulous planning—carrying glucose gels, adjusting my pump settings for exercise, and staying hyper-aware of how my body feels—but crossing that finish line will be worth every ounce of extra effort.\n\nTo the newly diagnosed: it gets easier. The math becomes second nature. You will learn how your body reacts to different foods, stress levels, and exercise routines. Don’t let this condition stop you from living the life you want. You control the diabetes; it doesn’t control you.',
      'tags': ['Type1Diabetes', 'T1D', 'ChronicIllness', 'Milestone'],
    },
    {
      'title': 'Recovering from Burnout: Reclaiming My Life',
      'content': 'For years, I wore my 80-hour work weeks like a badge of honor. I thought I was invincible until my body physically forced me to stop. The burnout was so severe that I couldn\'t look at a computer screen without getting a migraine, and the exhaustion felt deep in my bones. I was running on empty, fueled entirely by caffeine, adrenaline, and a toxic fear of failure.\n\nTaking a medical leave of absence was the hardest but most necessary decision of my life. The first few weeks were terrifying. Without my job, I didn\'t know who I was. I felt incredibly guilty for resting. But it took months of aggressive rest, therapy, and completely unlearning my relationship with productivity to feel human again. I had to realize that my worth as a human being is not tied to my economic output or how many items I cross off a to-do list.\n\nI slowly began rediscovering the things that brought me actual joy, divorced from any sort of hustle or monetization. I started baking, reading fiction, and taking walks without listening to a productivity podcast. \n\nToday, I have strict boundaries. I clock out at 5 PM. I leave my phone in another room on weekends. I say no to projects that I don\'t have the capacity for. If you feel yourself slipping into burnout, please listen to your body before it breaks down entirely. Rest is a requirement, not a reward for hard work.',
      'tags': ['BurnoutRecovery', 'MentalHealth', 'SelfCare', 'HealingJourney'],
    },
    {
      'title': 'Thriving with ADHD in Adulthood',
      'content': 'Getting diagnosed with ADHD at 30 was an absolute revelation. Suddenly, my entire life made sense—the chronic procrastination, the hyper-fixations that lasted exactly three weeks, the struggle to maintain basic routines, and the constant feeling of falling short of my potential. I wasn\'t lazy or undisciplined; my brain simply worked differently, starved for dopamine and struggling with executive function.\n\nStarting medication helped quiet the constant, chaotic noise in my head, but the real game-changer was learning to work with my brain instead of against it. I stopped forcing myself to use traditional planners that I inevitably abandoned. I built a system of visual cues, alarms, and externalized memory systems that actually works for my specific neurotype.\n\nI’ve also learned to embrace the positive aspects of ADHD. My hyper-focus allows me to dive deep into complex problem-solving at work, and my non-linear thinking helps me connect ideas that others might miss. It’s a double-edged sword, but understanding the blade makes all the difference.\n\nTo anyone diagnosed late in life: give yourself immense grace for the years you spent struggling. You are not broken. You just need a different operating manual, and the journey to figuring out what works for you is entirely worth the effort.',
      'tags': ['ADHD', 'Neurodivergent', 'AdultADHD', 'MentalHealthAwareness', 'Milestone'],
    },
    {
      'title': 'My First Marathon Post-Surgery',
      'content': 'When I tore my ACL two years ago in a skiing accident, the orthopedic surgeon told me my days of long-distance running were likely over. Running was my therapy, my escape, and my passion. Hearing that felt like a death sentence to my identity. For a few months, I spiraled into a deep depression, convinced my body had betrayed me permanently.\n\nBut eventually, I refused to give up. The physical therapy was grueling. There were setbacks, tears, and moments where I wanted to quit because the pain of a simple squat felt insurmountable. Slowly, over the course of eighteen months, I progressed from walking with crutches, to walking unassisted, to jogging lightly on a treadmill, to finally hitting the pavement again.\n\nToday, I crossed the finish line of my first post-surgery marathon! The feeling of running those final miles, knowing what my knee had been through, was incredibly emotional. I cried as I crossed the finish line. \n\nIt wasn\'t my fastest time, not by a long shot, but it was easily my proudest. Never let anyone tell you definitively what your body is incapable of. With patience, extreme stubbornness, and the right medical and physical therapy support, you can rebuild yourself.',
      'tags': ['PostSurgery', 'PhysicalTherapy', 'Resilience', 'Recovery', 'Milestone'],
    },
    {
      'title': 'Beating Insomnia: How I Finally Learned to Sleep',
      'content': 'If you\'ve never had chronic insomnia, it\'s hard to explain the sheer panic of watching the clock tick from 2 AM to 3 AM to 4 AM, knowing you have to be at work in three hours. For over a year, I was functioning on 2-3 hours of broken sleep a night. It severely affected my job performance, my relationships, and my overall sanity. I felt like a zombie walking through a waking nightmare.\n\nSleeping pills provided temporary relief but weren\'t a long-term fix, and I hated the groggy feeling the next day. What finally worked for me was Cognitive Behavioral Therapy for Insomnia (CBT-I). It was arguably harder than the insomnia at first. I had to undergo strict sleep restriction—limiting my time in bed to only 5 hours a night initially—and completely rebuild my sleep hygiene from the ground up.\n\nI removed all screens from my bedroom, established a rigid wind-down routine consisting of reading a physical book and gentle stretching, and learned how to challenge the catastrophic thoughts about not sleeping that were keeping my nervous system in hyper-arousal.\n\nLast night, I slept for 7 unbroken hours. I woke up feeling rested and clear-headed—a sensation I had completely forgotten existed. There is a way out of the insomnia trap, it just requires immense discipline and a willingness to confront your anxiety head-on.',
      'tags': ['Insomnia', 'SleepHealth', 'CBTI', 'HealingJourney'],
    },
    {
      'title': 'A Year of Sobriety: The Best Decision I Ever Made',
      'content': 'Today marks exactly 365 days without a single drop of alcohol. When I first decided to quit, I was terrified. Alcohol was my primary social crutch, my go-to stress reliever after a hard day, and my ultimate coping mechanism. I genuinely didn\'t know who I was without a drink in my hand at a party.\n\nThe first few months were incredibly difficult. I had to face raw emotions I had been actively numbing for a decade. I had to learn how to sit with anxiety, boredom, and sadness without reaching for a bottle. I lost a few friends who only wanted a drinking buddy, and navigating social events felt like learning how to walk all over again.\n\nBut as the fog cleared, I discovered a level of clarity and peace I never knew existed. My baseline anxiety has plummeted. My sleep is incredibly deep and restorative. My relationships are finally authentic, based on real connection rather than shared intoxication. I have so much more time and money to invest in hobbies I actually care about.\n\nIf you\'re questioning your relationship with alcohol, just try taking a break. You don\'t have to hit a dramatic "rock bottom" to decide that drinking is no longer serving you. Life is so much brighter, calmer, and more beautiful on this side.',
      'tags': ['Sobriety', 'AlcoholFree', 'RecoveryJourney', 'Recovery', 'Milestone'],
    },
    {
      'title': 'Navigating the Ups and Downs of IBS',
      'content': 'Irritable Bowel Syndrome is the chronic condition no one wants to talk about. It’s embarrassing, unpredictable, and completely disruptive to daily life. For a long time, I let fear of sudden flare-ups dictate where I went, what I did, and who I saw. I mapped out bathrooms everywhere I went and frequently canceled plans at the last minute, leading to intense social isolation.\n\nWorking with a registered dietitian to complete the low-FODMAP elimination diet changed my life. It was a tedious, difficult process of tracking everything I ate, but we finally identified my specific trigger foods (goodbye forever, garlic and onions!). I also started practicing gut-directed hypnotherapy, which helped calm the incredibly strong brain-gut connection that triggered my symptoms during stressful times.\n\nI’ve also learned to be more open about my condition. Telling my close friends and coworkers about my IBS took the shame out of it. When I have to rush out of a meeting or decline a certain type of food, I no longer have to make up elaborate excuses. \n\nI still have bad days, but I no longer live in constant fear of my own digestive system. For anyone struggling with chronic gut issues, keep advocating for yourself until you find a management plan that works. Relief is possible.',
      'tags': ['IBS', 'GutHealth', 'ChronicIllness', 'HealingJourney'],
    },
    {
      'title': 'Embracing My Scars: Life After Severe Burns',
      'content': 'Three years ago, a terrible accident in the kitchen left me with third-degree burns across my arms and chest. The physical pain of the initial injury and the subsequent skin graft surgeries was excruciating. But the emotional pain of seeing my drastically altered body in the mirror was far worse. I spent a year hiding under long sleeves and high-necked shirts, even in the dead of summer, terrified of the pitying looks from strangers.\n\nIt took intensive trauma therapy to help me process the accident itself (the PTSD was severe) and begin the long journey of accepting my new reflection. I started following burn survivor accounts online, and seeing their confidence and refusal to hide their bodies inspired me deeply. They showed me that beauty and scarring are not mutually exclusive.\n\nToday, I wore a tank top in public for the first time in three years. I caught a few people staring, but instead of shrinking away and pulling on a sweater, I held my head high. My scars are proof that I survived something horrific. They are a literal map of my resilience and my body\'s incredible ability to heal itself. I am finally proud of the skin I am in.',
      'tags': ['BurnSurvivor', 'BodyPositivity', 'TraumaRecovery', 'Recovery'],
    },
    {
      'title': 'Managing Asthma as an Athlete',
      'content': 'Growing up, I was always the kid on the sidelines using a rescue inhaler while everyone else played sports. I convinced myself that athletics just weren\'t in the cards for me due to my severe asthma. Gym class was a nightmare of wheezing and embarrassment, and I eventually just stopped trying to be active altogether.\n\nIn my mid-twenties, I decided to aggressively challenge that narrative. I was tired of feeling frail. I worked closely with my pulmonologist to develop an aggressive, proactive management plan, including daily controller medications and a strict warm-up protocol before exercise. I started swimming, an incredibly lung-friendly sport, which actually helped increase my overall lung capacity and breath control.\n\nLast weekend, I competed in my first sprint triathlon. It took careful pacing, constant monitoring of my breathing, and a perfectly timed puff of my inhaler before the run portion, but I did it. I crossed the finish line feeling incredibly strong.\n\nHaving a chronic condition doesn\'t mean giving up on your athletic goals—it just means you have to train smarter, be more patient with your progression, and listen to your body much closer than everyone else.',
      'tags': ['Asthma', 'ChronicIllness', 'AthleteLife', 'Milestone'],
    },
    {
      'title': 'The Silent Struggle of Migraines',
      'content': 'People who have never experienced one often dismiss migraines as "just a bad headache." They don\'t understand the visual aura that blinds you, the debilitating nausea, the extreme sensitivity to light and sound that forces you into a dark room, and the cognitive "hangover" (the post-drome) that lasts for days after the pain subsides.\n\nFor years, I was getting 10-15 migraines a month. I felt like a burden to my family, constantly missing out on events, and I was incredibly unreliable at work. The fear of triggering an attack dominated every decision I made. Finding the right preventative medication was a grueling, years-long game of trial and error.\n\nAfter failing three different classes of older drugs—beta blockers, antidepressants, and anti-seizure meds—we finally tried a CGRP inhibitor injection. Within two months, it gave me my life back. It was nothing short of miraculous. \n\nI now get maybe one minor migraine a month, and it is usually easily manageable with an acute rescue medication. Don\'t settle for suffering. Keep pushing your neurologist for new treatments, because migraine science is advancing rapidly, and new options are becoming available every year.',
      'tags': ['MigraineAwareness', 'ChronicPain', 'InvisibleIllness', 'HealingJourney'],
    },
    {
      'title': 'Weight Loss Journey: Celebrating Health, Not Just Numbers',
      'content': 'I\'ve spent most of my adult life battling obesity and riding the exhausting yo-yo dieting rollercoaster. I would lose 50 pounds through extreme caloric restriction and punishing cardio, only to inevitably burn out, binge, and gain back 60 pounds. My entire self-worth was tied to the number on the scale every morning.\n\nTwo years ago, I decided to stop focusing on the scale entirely and start focusing on how my body felt and performed. I threw out my scale. I began strength training to feel strong and capable, not to burn calories. I focused on eating more protein and vegetables because they gave me sustained energy and made my skin glow, not because I was restricting myself from eating carbs.\n\nI’ve steadily lost 80 pounds over the last two years, but more importantly, my blood pressure is completely normal, my joints don\'t ache when I walk, and I can finally keep up with my kids at the park without losing my breath. The non-scale victories are what keep me going. Realizing that health is a lifelong habit and a form of self-respect, not a sprint to a finish line or a punishment, changed everything.',
      'tags': ['WeightLossJourney', 'HealthyHabits', 'StrengthTraining', 'Milestone', 'Recovery'],
    },
  ];

  /// Returns a random dummy post containing a 'title', 'content', and 'tags' list.
  static Map<String, dynamic> getRandomPost() {
    return _dummyPosts[_random.nextInt(_dummyPosts.length)];
  }
}
